backend:
  name: github
  repo: cs-canigo/portal
  branch: master    
  #base_url: https://8nfrl3q3vj.execute-api.eu-west-1.amazonaws.com/default/cms/
  base_url: https://cms-auth.fly.dev/

media_folder: "static/images"
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}/{{month}}/{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Descripció", name: "description", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Seccions", name: "sections", widget: "list"}
      - {label: "Etiquetes", name: "tags", widget: "list"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Imatge", name: "imatge", widget: "image"}
      - {label: "Key", name: "key", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}