backend:
  name: github
  repo: cs-canigo/portal
  branch: master    
  #base_url: https://8nfrl3q3vj.execute-api.eu-west-1.amazonaws.com/default/cms/
  base_url: https://cms-auth.fly.dev/
  client_id: 51c93d314ea3c142bf03

media_folder: "static/images"
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "arquitectura"
    label: "Arquitectura"
    folder: "content/arquitectura" 
    identifier_field: "name"
    create: true 
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Descripció", name: "description", widget: "text"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Seccions", name: "sections", widget: "list"}
      - {label: "Àlies (url)", name: "aliases", widget: "list"}
      - {label: "Ordre", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "plataformes"
    label: "Plataformes"
    folder: "content/plataformes" 
    create: true 
    fields:
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Descripció", name: "description", widget: "text"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Seccions", name: "sections", widget: "list"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Àlies (url)", name: "aliases", widget: "list"}
      - {label: "Ordre", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "destacats"
    label: "Destacats"
    folder: "content/destacats" 
    create: true 
    fields:
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Descripció", name: "description", widget: "text"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Enllaç", name: "enllac", widget: "string"}
      - {label: "Seccions", name: "sections", widget: "list"}
      - {label: "Key", name: "key", widget: "string"}

  - name: "destacats-related"
    label: "Destacats (relacionats)"
    folder: "content/destacats-related" 
    create: true 
    fields:
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Descripció", name: "description", widget: "text"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Seccions", name: "sections", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "blog"
    label: "Blog"
    folder: "content/blog" 
    create: true 
    slug: "{{slug}}"
    path: '{{year}}/{{month}}/{{day}}'
    sortable_fields: ['date']
    fields:
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Descripció", name: "description", widget: "text"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Seccions", name: "sections", widget: "list"}
      - {label: "Etiquetes", name: "tags", widget: "list"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Imatge", name: "imatge", widget: "image"}
      - {label: "Key", name: "key", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    
  - name: "howtos"
    label: "How To's"
    folder: "content/howtos" 
    create: true 
    fields:
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Descripció", name: "description", widget: "text"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Seccions", name: "sections", widget: "list"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Key", name: "key", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "noticies"
    label: "Notícies"
    folder: "content/noticies" 
    create: true 
    fields:
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Descripció", name: "description", widget: "text"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Seccions", name: "sections", widget: "list"}
      - {label: "Categories", name: "categories", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "drafts"
    label: "Drafts"
    folder: "content/drafts" 
    create: true 
    fields:
      - {label: "Títol", name: "title", widget: "string"}
      - {label: "Descripció", name: "description", widget: "text"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Seccions", name: "sections", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
